---
  title: "Preprocessing Gene Expression of Lung Cancer (TCGA-LUSC)"
output:
  # pdf_document: default
  html_document: 
  default
github_document: 
  df_print: paged
html_preview: FALSE
keep_html: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_format = "all") })      
---
  
  
  ```{r error=TRUE, message=FALSE, warning=FALSE, include=FALSE, purl=FALSE, results='hide'}
## This chunk automatically generates a text .R version of this script when running within knitr.
input  = knitr::current_input()  # filename of input document
output = paste(tools::file_path_sans_ext(input), 'R', sep = '.')
try(knitr::purl(input,output,documentation=2,quiet=T), silent = TRUE)
# Avoid duplicate label error of knitr::purl
options(knitr.duplicate.label = 'allow')
# Code to browse the markdown file with renderized images.
knitr::opts_chunk$set(
  fig.path = "figs/render-"
)
```


# Installing and Loading Libraries            


```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(annotables) # BiocManager::install("annotate")
# 
 packages_bioconductor = c("clusterProfiler", "org.Hs.eg.db", "ReactomePA", "DOSE")
# 
# #use this function to check if each package is on the local machine
# #if a package is installed, it will be loaded
# #if any are not, the missing package(s) will be installed from Bioconductor and loaded
 package.check <- lapply(packages_bioconductor, FUN = function(x) {
   if (!require(x, character.only = TRUE)) {
     BiocManager::install(x, dependencies = TRUE)
     library(x, character.only = TRUE)
   }
 })
 #install.packages("mlr3extralearners")
 install.packages("remotes")
 remotes::install_github("mlr-org/mlr3extralearners")
packages_cran = c("tidyverse", "bestNormalize", "mlr3", "mlr3verse", "mlr3proba", "mlr3extralearners",  "survival", "mRMRe", "xgboost", "glmnet", "gbm")

install.packages("remotes")
remotes::install_github("xoopR/param6")

install.packages("mlr3proba", repos = "https://mlr-org.r-universe.dev")

#install.packages("devtools")
devtools::install_github("petersonR/bestNormalize")

remotes::install_github("mlr-org/mlr3verse")

install.packages("xgboost")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed from CRAN and loaded
package.check <- lapply(packages_cran, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})
library(annotables)
library(tictoc)  devtools::install_github("collectivemedia/tictoc")
rm(packages_cran, packages_bioconductor, package.check)
```


# Selecting genes for TCGA-LUSC

```{r}
load("../data/lusc_count.RData")
lusc.annot$symbol.dot <-  gsub("-", ".", lusc.annot$symbol, fixed = T)
rownames(lusc.count)  <-  gsub("-", ".", rownames(lusc.count), fixed = T)
rownames(lusc.count)  <-  gsub("//", ".", rownames(lusc.count), fixed = T)
rownames(lusc.count)  <-  gsub("/", ".", rownames(lusc.count), fixed = T)
# Select genes ----
genes_DEA_M0 <- readLines("../data/genes.DEA.M0.vs.M1.lst")
genes_DEA_NT <- readLines("../data/genes.DEA.NT.vs.TP.lst")
genes_DEA_TF <- readLines("../data/genes.DEA.TF.vs.WT.lst")
genes_risk <- readLines("../data/genes_mutated.highrisk.lst")
genes_eqtls <- readLines("../data/genes_lung.lst")

#gsign_kidney <- read_delim("../data/genes_signatures_papers_kidney.csv", quote = "\"", "\t", escape_double = FALSE, trim_ws = TRUE)
#gsign_kidney <- as.data.frame(gsign_kidney)
#gsign_kidney$signature <- str_split(gsign_kidney$signature,",")
#gsign_kidney$id <- paste0("sign.",row.names(gsign_kidney))
#rownames(gsign_kidney) <- gsign_kidney$id
#genes_papers <- unlist(gsign_kidney$signature)


genes_selection <-  union(union(union(union(genes_DEA_M0, genes_DEA_NT), genes_risk), genes_DEA_TF), genes_eqtls)
# Checking missing genes ----

gene_missing <- union(union(union(setdiff(genes_DEA_TF, lusc.annot$symbol.dot),setdiff(genes_DEA_NT, lusc.annot$symbol.dot)),setdiff(genes_DEA_TF, lusc.annot$symbol.dot)),setdiff(genes_risk, lusc.annot$symbol.dot))
#gene_missing <- setdiff(genes_eqtls, lusc.annot$symbol.dot)
#gene_missing <- setdiff(genes_DEA_TF, lusc.annot$symbol.dot)
#gene_missing <- setdiff(genes_DEA_NT, lusc.annot$symbol.dot)
#gene_missing <- setdiff(genes_risk, lusc.annot$symbol.dot)
#gene_missing

# gene_missing on genes_DEA_eqtls
#[1] "NKX2-1"            "RP1-251M9.3"       "GS1-600G8.5"      
#[4] "RP11-302F12.1"     "RP11-88I21.2"      "RP11-513N24.1"    
#[7] "FAM92B"            "CCDC108"           "AC079630.2"       
#[10] "AC008268.1"        "RP11-434I12.3"     "RP11-77A13.1"     
#[13] "RP11-476D10.1"     "RP11-15K2.2"       "RP11-635O16.2"    
#[16] "WISP2"             "PIH1D3"            "AC000111.6"       
#[19] "TCEB1P28"          "LRRC6"             "NKX2-8"           
#[22] "WDR63"             "ALPPL2"            "T"                
#[25] "NKX6-3"            "C9orf9"            "DPCR1"            
#[28] "ARMC4"             "C2orf54"           "GRAMD2"           
#[31] "AC079741.2"        "CCDC129"           "RP4-539M6.14"     
#[34] "FAM159A"           "ANKRD20A2"         "C11orf88"         
#[37] "MAATS1"            "RP11-723O4.6"      "KRTAP13-1"        
#[40] "C1orf228"          "SNORD114-14"       "RNU6-446P"        
#[43] "RNU6-223P"         "RNU1-134P"         "SNORD114-19"      
#[46] "SNORD113"          "RNU5E-8P"          "SNORA42"          
#[49] "RNU6-509P"         "RNU6-1066P"        "RNU1-87P"         
#[52] "RNU6-899P"         "SNORD74"           "RNA5-8SP3"        
#[55] "RNU6-1164P"        "RNU6-1082P"        "SNORD114-15"      
#[58] "RNU6-621P"         "RNU6-967P"         "SNORD114-12"      
#[61] "RP11-77K12.4"      "RP11-126H7.4"      "IGKV1OR-3"        
#[64] "RP11-352D3.2"      "RNU6-841P"         "RNU6-1083P"       
#[67] "RNU6-1310P"        "RNU6-1181P"        "RNU6-514P"        
#[70] "RNU6-5P"           "RNU6-196P"         "RNU6-790P"        
#[73] "RNU6-1152P"        "MIR194-1"          "MIR650"           
#[76] "AC115099.1"        "IGKV6D-41"         "IGHV1-45"         
#[79] "AP000428.1"        "RNU1-149P"         "RNU11-6P"         
#[82] "RNU1-56P"          "RP3-382I10.7"      "RP11-364P2.2"     
#[85] "RP11-509M23.1"     "DUSP8P3"           "RP5-1057J7.1"     
#[88] "AC008166.1"        "RP1-232L24.2"      "RP4-724P12.1"     
#[91] "AL133232.1"        "AC004673.1"        "AC103996.1"       
#[94] "RNU6-955P"         "RNU6-1064P"        "AC010999.1"       
#[97] "RNU6-402P"         "RNU6-1203P"        "RNU6-293P"        
#[100] "AC008836.1"        "AL033378.1"        "RP11-93B14.4"     
#[103] "RP11-554D15.1"     "RP11-728K20.1"     "AC097468.4"       
#[106] "AC104389.16"       "RP1-15D23.2"       "RP1-102E24.9"     
#[109] "RP13-228J13.6"     "ATP13A4-AS1"       "RP11-325P15.1"    
#[112] "RP4-683M8.2"       "RP1-163G9.2"       "RP11-1L9.1"       
#[115] "RP11-550C4.6"      "CTA-384D8.31"      "RP4-675G8.3"      
#[118] "AC011893.3"        "RP11-122M14.3"     "AC093787.1"       
#[121] "RP11-533N14.3"     "RP11-95I16.2"      "AC069213.4"       
#[124] "ATP5G1P5"          "LL22NC03-30E12.13" "AC007365.4"       
#[127] "RP11-399H11.3"     "RP11-361M4.1"      "AC073091.2"       
#[130] "RP11-568A7.2"      "SRGAP3-AS2"        "RP1-186E20.1"     
#[133] "RP11-746P2.5"      "RP11-91I11.1"      "MED4-AS1"         
#[136] "RP11-498J9.2"      "RP11-193I22.2"     "AC023669.1"       
#[139] "RP4-738P11.4"      "AC092569.2"        "RP5-1193P9.2"     
#[142] "AC092580.3"        "AOAH-IT1"          "RP11-331H2.4"     
#[145] "AC007349.7"        "AC004159.1"        "AC006994.2"       
#[148] "RP1-27K12.2"       "AP002856.5"        "RP11-432J24.2"    
#[151] "AL138479.3"        "AC011899.10"       "RP11-62I21.1"     
#[154] "RP11-203H2.1"      "RP11-13E1.5"       "RP11-342C20.2"    
#[157] "IQCA1-AS1"         "RP11-86A5.1"       "RP4-667H12.4"     
#[160] "RP11-288L9.1"      "RP11-353N4.5"      "TMEM212-AS1"      
#[163] "RP13-130D24.1"     "XX-C2158C12.1"     "AL109767.1"       
#[166] "RP13-16H11.5"      "RP11-59O6.3"       "RP11-645N11.3"    
#[169] "MYO16-AS1"         "AC003092.1"        "RP11-8J9.5"       
#[172] "AC002331.1"        "RP11-95P9.1"       "DLX2-AS1"         
#[175] "RP11-159H3.1"      "AC003092.2"        "AC128709.2"       
#[178] "RP11-85G21.2"      "RP5-1155K23.4"     "AC009498.1"       
#[181] "RP3-461P17.9"      "AC093911.1"        "RP11-730A19.7"    
#[184] "AC093668.1"        "IGKV1-37"          "IGKV1D-33"        
#[187] "TM4SF1-AS1"        "FAM195CP"          "AC090602.2"       
#[190] "RP11-469J4.3"      "IGKV1D-17"         "RP11-180K7.1"     
#[193] "RP11-14I2.2"       "RP11-281P11.1"     "RP11-254G11.1"    
#[196] "CTD-2292M14.1"     "RP11-125O18.1"     "RP11-302F12.3"    
#[199] "RP11-287F9.2"      "RP11-206P5.2"      "RP11-661C8.2"     
#[202] "CTD-2113L7.1"      "RP11-447E20.1"     "RP11-1C1.5"       
#[205] "CTC-529L17.1"      "AC195454.1"        "RP11-751L19.1"    
#[208] "CTC-441N14.1"      "CTD-2544H17.1"     "CTB-138E5.1"      
#[211] "RP11-212F11.1"     "CTC-359M8.1"       "AF196779.12"      
#[214] "CTD-2024P10.1"     "RP11-647P12.1"     "RP11-366M4.15"    
#[217] "RP13-577H12.2"     "RP11-116A1.1"      "RP11-158C21.2"    
#[220] "RP11-138B4.1"      "RP11-540D14.8"     "RP11-385D13.1"    
#[223] "RNU7-175P"         "AC090420.1"        "RNU6-416P"        
#[226] "RNU6-314P"         "RNU6-1069P"        "SNORD45"          
#[229] "RNU6-1282P"        "RNU2-44P"          "RNU6-789P"        
#[232] "RNU6-1057P"        "RNU7-35P"          "RP1-84O15.2"      
#[235] "RP11-550I15.1"     "CTA-392E5.1"       "IGLV3-6"          
#[238] "CTC-756D1.1"       "RP11-44K6.2"       "AC226119.5"       
#[241] "CTB-43E15.1"       "RP11-470M17.2"     "CTD-3107M8.2"     
#[244] "IGHVIII-51-1"      "RP11-179A10.1"     "RP11-304C12.3"    
#[247] "RP11-84A19.3"      "RP11-429J17.5"     "RP11-56A10.1"     
#[250] "INMT-FAM188B"      "RP11-167J8.3"      "RP11-794P6.6"     
#[253] "CTD-3012A18.1"     "RP11-655M14.12"    "RP11-655M14.4"    
#[256] "RP11-428C19.5"     "RP11-734C14.2"     "RP13-631K18.5"    
#[259] "CTD-2531D15.4"     "RP11-63D14.1"      "CTA-797E19.2"     
#[262] "RP11-59N23.3"      "RP11-666F17.2"     "RP11-2A1.1"       
#[265] "RP11-359M6.1"      "RP11-896J10.3"     "RP11-804F13.2"    
#[268] "RP11-139E19.2"     "RP11-148E17.1"     "RP11-74K11.2"     
#[271] "RP4-816N1.7"       "RP11-77I22.4"      "RP11-412H8.2"     
#[274] "RP11-148B3.2"      "RP11-404P21.5"     "RP1-292L20.2"     
#[277] "RP11-543C4.3"      "RP11-356K23.1"     "RP11-813I20.2"    
#[280] "RP11-589M4.2"      "RP11-259K15.2"     "RP11-100M12.2"    
#[283] "RP11-203M5.6"      "RP11-60L3.1"       "RP11-26L20.3"     
#[286] "RP11-276M12.1"     "RP11-351M8.2"      "RP11-143J24.1"    
#[289] "CTA-363E6.1"       "CTA-363E6.2"       "RP11-322D14.2"    
#[292] "RP11-120K18.3"     "RP11-351A20.1"     "LA16c-325D7.1"    
#[295] "RP11-612A1.1"      "AC235953.1"        "AC017104.1"       
#[298] "RP11-146G7.2"      "RP11-789C17.5"     "BX649553.2"       
#[301] "AC063932.1"        "MIR3175"           "RP11-21G15.1"     
#[304] "CTD-2501B8.1"      "AC011450.1"        "RP11-169I9.2"     
#[307] "AC005288.1"        "AC005256.1"        "CTD-2378E21.1"    
#[310] "RP11-64C12.7"      "CTD-2369P2.8"      "RP11-188I24.1"    
#[313] "RP11-10I6.2"       "CTD-2265O21.7"     "CTC-518B2.10"     
#[316] "RP11-687D19.1"     "RP1-102K2.8"       "CTC-246B18.10"    
#[319] "AC092071.1"        "CTD-3187F8.6"      "CTD-3214H19.16"   
#[322] "CTC-518B2.8"       "LA16c-380H5.3"     "IGHV3OR16-12"     
#[325] "RP11-168P13.1"     "RP11-455J15.1"     "RP11-142I2.1"     
#[328] "RP11-666O2.1"      "RP11-68E19.1"      "RP11-141C7.3"     
#[331] "RP11-297J22.1"     "MIR92B"            "RNU6-85P"         
#[334] "AC226119.4"        "RP11-332J15.4"     "RNU4-5P"          
#[337] "AC026703.1"        "RP11-54O7.18"      "RP11-85B7.5"      
#[340] "IGKV2-40"          "INO80B-WBP1"       "RP4-545L17.12"    
#[343] "RP1-66H9.1"        "AC145212.2"        "RP11-385J1.3"     
#[346] "RP11-844G16.3"     "RP11-101E5.1"      "FAS-AS1"          
#[349] "RP11-397O8.7"      "AC009499.1"        "RP11-106D4.3"     
#[352] "RP11-144A16.8"     "RP11-400G3.5"      "AC026254.1"       
#[355] "RP11-60L3.6"       "AC138649.1"        "MIR29A"           
#[358] "RP1-229K20.9"      "AC005071.2"        "CTD-2537I9.15"    
#[361] "AC234582.1"        "RP11-79C6.2"       "RP11-472K17.3"    
#[364] "AC234582.2"        "RP11-191F9.1"      "CH17-140K24.2"    
#[367] "CTC-312O10.3"      "CH507-42P11.7"     "RP1-59D14.8"      
#[370] "RP11-218I21.2"     "RP11-83B20.8"      "AC010480.1"       
#[373] "RP4-587D13.1"      "AL355480.2"        "RP11-294C11.4"    
#[376] "AC018816.1"        "AC011380.1"        "AL136115.1"       
#[379] "RP11-237N19.3"     "AP001187.1"        "AL391095.1"       
#[382] "AC012363.2"        "AC016959.1"        "AP000237.1"       
#[385] "AC091053.2" 


# gene_missing on genes_DEA_TF
#[1] "MARCHF11-DT"

# gene_missing on genes_risk

#[1] "BOD1L"    "C3orf30"  "C10orf79" "CCDC108"  "COLL11A1" "DARC"    
#[7] "DBC1"     "DUSP27"   "GPR128"   "GUGY1A2"  "INADL"    "MK167"   
#[13] "NKX2-2"   "ODZ1"  

# gene_missing on genes_DEA_NT
#[1] "NKX3-2"          "NKX2-3"          "MIR9-1HG"        "NKX2-4"         
#[5] "NKX2-2"          "NKX6-1"          "IGF2BP2-AS1"     "NKX6-3"         
#[9] "NKX2-5"          "KRTAP19-1"       "H1-5"            "UMODL1-AS1"     
#[13] "B3GALT5-AS1"     "KRTAP17-1"       "NPSR1-AS1"       "KRTAP4-1"       
#[17] "RNU1-70P"        "RNU1-38P"        "RNU5E-8P"        "RNU5B-4P"       
#[21] "RNU6-353P"       "RNU6-967P"       "RNU6-438P"       "FAM83A-AS1"     
#[25] "TRBV20OR9-2"     "CALML3-AS1"      "KRTAP5-6"        "RNU6-140P"      
#[29] "KRTAP29-1"       "KRTAP2-3"        "KRTAP3-1"        "H1-12P"         
#[33] "KIRREL3-AS3"     "LL22NC03-63E9.3" "RNU6-955P"       "RNU6-705P"      
#[37] "POU6F2-AS1"      "SOX1-OT"         "ARHGEF2-AS1"     "LEMD1-DT"       
#[41] "CDKN2A-DT"       "PGM5-AS1"        "OSTM1-AS1"       "LHFPL3-AS2"     
#[45] "LRRK2-DT"        "CYP4A22-AS1"     "CADM3-AS1"       "PACRG-AS3"      
#[49] "ADGRF5-AS1"      "SATB2-AS1"       "TMEM252-DT"      "FGF12-AS3"      
#[53] "NAALADL2-AS2"    "ERVMER34-1"      "SLC2A1-AS1"      "SOX21-AS1"      
#[57] "RAPGEF4-AS1"     "MELTF-AS1"       "TBX18-AS1"       "SRGAP3-AS2"     
#[61] "CNIH3-AS1"       "NKX1-2"          "TFAP2A-AS1"      "MAGEA4-AS1"     
#[65] "TRPM2-AS"        "FEZF1-AS1"       "FOXD3-AS1"       "HHATL-AS1"      
#[69] "APCDD1L-DT"      "CLEC12A-AS1"     "ABCA9-AS1"       "CHODL-AS1"      
#[73] "DLX6-AS1"        "PGM5P4-AS1"      "GRHL3-AS1"       "TBC1D26-AS1"    
#[77] "PTPRN2-AS1"      "XXYLT1-AS1"      "POU6F2-AS2"      "KCNH1-IT1"      
#[81] "DEPDC1-AS1"      "LANCL1-AS1"      "TFPI2-DT"        "B3GALT1-AS1"    
#[85] "BARX1-DT"        "SYN3-AS1"        "ELFN1-AS1"       "MYO16-AS1"      
#[89] "ATP13A5-AS1"     "DLX2-DT"         "MLIP-IT1"        "HOXD-AS2"       
#[93] "KCNMB2-AS1"      "RNU7-159P"       "ATP6V1B1-AS1"    "PDZRN3-AS1"     
#[97] "LSAMP-AS1"       "HOXA11-AS"       "ADAMTS9-AS1"     "ADAMTS9-AS2"    
#[101] "HOXB-AS4"        "SOX2-OT"         "MNX1-AS1"        "ARNTL2-AS1"     
#[105] "KLRK1-AS1"       "OTX2-AS1"        "C5orf34-AS1"     "GDNF-AS1"       
#[109] "KRTAP9-12P"      "GPM6A-DT"        "IRX4-AS1"        "TMEM132D-AS1"   
#[113] "CTD-3080P12.3"   "CTD-2194D22.4"   "IL20RB-AS1"      "NEUROG2-AS1"    
#[117] "HOXC13-AS"       "CEP72-DT"        "ESAM-AS1"        "HOXC-AS2"       
#[121] "MARCHF11-DT"     "HOXC-AS1"        "KHDRBS2-OT1"     "THOC3-AS1"      
#[125] "ZFPM2-AS1"       "TMEM108-AS1"     "HOXC-AS3"        "TACR3-AS1"      
#[129] "RNU6-917P"       "RNU6-725P"       "RNU6-548P"       "HOXA10-AS"      
#[133] "IKBKB-DT"        "IGHV7-40"        "ZFHX4-AS1"       "FER1L6-AS2"     
#[137] "NRG1-IT1"        "MAFA-AS1"        "MPPED2-AS1"      "BBOX1-AS1"      
#[141] "SLC17A6-DT"      "NECTIN1-DT"      "INMT-MINDY4"     "TDH-AS1"        
#[145] "GRM5-AS1"        "TSKU-AS1"        "NECTIN1-AS1"     "MIR9-3HG"       
#[149] "CABP1-DT"        "PPP1R14B-AS1"    "SLCO1B3-SLCO1B7" "KIRREL3-AS1"    
#[153] "G2E3-AS1"        "NOVA1-DT"        "LHX5-AS1"        "DIO2-AS1"       
#[157] "EGLN3-AS1"       "CDH8-AS1"        "INSYN1-AS1"      "VPS9D1-AS1"     
#[161] "PAQR5-DT"        "SSTR5-AS1"       "NQO1-DT"         "HID1-AS1"       
#[165] "GATA6-AS1"       "MAGEA10-MAGEA5"  "DSG1-AS1"        "TCF4-AS1"       
#[169] "MAP4K1-AS1"      "LDLRAD4-AS1"     "RUNDC3A-AS1"     "CBARP-DT"       
#[173] "IGFL2-AS1"       "ERVV-2"          "ERVV-1"          "IGLVIVOR22-1"   
#[177] "BCAN-AS1"        "AFAP1-AS1"       "LHX1-DT"         "PGM5P3-AS1"     
#[181] "CH507-42P11.6"   "KCNIP4-IT1"      "SH3PXD2A-AS1"  

BiocManager::install("mygene")
library(mygene)
#gene_missing0 <- gene_missing
##  Multiple Gene ID Convert
gene_missing <- gsub(".", "-", gene_missing, fixed = T)
gene_missing <- as.matrix(gene_missing)
gene_missing1 <- queryMany(gene_missing, scopes="symbol", fields="symbol", species="human")
#mat_id_convert = c()
#for(i in 1:nrow(gene_missing)){
#  out <- query(q=gene_missing[i], size=1, returnall=FALSE)
#  mat_id_convert  <- rbind(mat_id_convert,out)
#}
#gene_missing <- cbind(gene_missing, mat_id_convert)
#rm(i, mat_id_convert, out)
gene_missing1 <- data.frame(gene_missing1,row.names = NULL)
colnames(gene_missing) <- c("previous_ID","symbol","Label")
gene_missing <- data.frame(gene_missing)
gene_missing$Symbol <- gsub("C10orf4", "FRA10AC1", gene_missing$Symbol)
gene_missing$Symbol <- gsub("C17orf79", "COPRS", gene_missing$Symbol)
gene_missing$Symbol <- gsub("CNN1G", "CNN1", gene_missing$Symbol)
gene_missing$Symbol <- gsub("SMIM37", "LINC00116", gene_missing$Symbol)
rownames(gene_missing) <- gene_missing$previous_ID
# EXOC3L2 ENSG00000283632 - ?
#        previous_ID   Symbol             Label
# out           MTLN     MTLN           Missing
# out.1     ERVFRDE1 ERVFRD-1             Trust
# out.2      FAM123A    AMER2     Predict Trust
# out.3       VEGFR1     FLT1             Trust
# out.4       VEGFR2      KDR     Predict Trust
# out.5       VEGFR3     FLT4             Trust
# out.6        HIF2A    EPAS1             Trust
# out.7        PD-L1    CD274             Trust
# out.8        IFN-G     IFNG     Predict Trust
# X              PD1    PDCD1 Predict Suspicion
# out.9        PD-L2 PDCD1LG2             Trust
# out.10        TIM3   HAVCR2             Trust
# out.11     EXOC3L2  EXOC3L2             Trust
# out.12         FYB     FYB1     Predict Trust
# out.13      ADRBK1     GRK2             Trust
g2subs <- intersect(gene_missing$previous_ID, genes_risk)
genes_risk <- union(setdiff(genes_risk, g2subs), gene_missing[g2subs, "Symbol"])
write(genes_risk,  file = "../3_gene_mutational_survival/genes_mutated.highrisk.lst")
g2subs <- intersect(gene_missing$previous_ID, genes_papers)
genes_papers <- union(setdiff(genes_papers, g2subs), gene_missing[g2subs, "Symbol"])
write(genes_papers,  file = "../data/genes_papers.lst")
setdiff(gene_missing$Symbol, lusc.annot$symbol)
rm(g2subs)
rm(gene_missing, genes_DEA_M0, genes_DEA_NT, genes_risk, genes_papers, genes_eqtls)
```

#  Select TCGA-lusc count and Combine data to clinical data  

```{r}
lusc.data <- data.frame(t(lusc.count[rownames(lusc.count) %in% genes_selection,]))
lusc.data <- lusc.data[lusc.clini[lusc.clini$sample.type == "TP","codes"],]
lusc.data <- cbind(lusc.clini[rownames(lusc.data),  c("obs.time", "status", "age", "gender", "prior.dx")], lusc.data )
lusc.data$obs.time <- round(lusc.data$obs.time, digits = 0)
lusc.data$status <- as.numeric(lusc.data$status)
lusc.data$age <- as.numeric(lusc.data$age)
lusc.data$gender <- as.numeric(lusc.data$gender)-1
lusc.data$prior.dx <- as.numeric(lusc.data$prior.dx)-1
lusc.data <- lusc.data[data$obs.time > 0,]

save(lusc.data, file = "../data/1.data.count.rda", compress = T)
```
